apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-keycloak
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-keycloak
  source:
    repoURL: https://github.com/zdmooc/gitops-platform.git
    targetRevision: main
    path: charts/keycloak
    helm:
      releaseName: keycloak
      values: |-
        auth:
          adminUser: admin
          adminPassword: admin
        proxy: edge
        postgresql:
          enabled: true
          global:
            storageClass: crc-csi-hostpath-provisioner
          primary:
            persistence:
              size: 1Gi
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
