global:
  storageClass: crc-csi-hostpath-provisioner

podSecurityContext:
  enabled: false
containerSecurityContext:
  enabled: false

auth:
  adminUser: admin
  adminPassword: admin

postgresql:
  enabled: true
  auth:
    postgresPassword: postgres
    username: keycloak
    password: keycloak
    database: keycloak
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
  volumePermissions:
    enabled: true

podAnnotations: {}

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    memory: 1Gi
