apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-postgres
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-db
  source:
    repoURL: https://github.com/zdmooc/gitops-platform.git
    targetRevision: main
    path: charts/postgresql
    helm:
      releaseName: postgresql
      values: |-
        global:
          storageClass: crc-csi-hostpath-provisioner
        auth:
          postgresPassword: postgres
        primary:
          persistence:
            size: 1Gi
        volumePermissions:
          enabled: true
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
