global:
  storageClass: crc-csi-hostpath-provisioner

auth:
  enablePostgresUser: true
  postgresPassword: postgres

primary:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  persistence:
    enabled: true
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

volumePermissions:
  enabled: true

shmVolume:
  enabled: true
