apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  source:
    repoURL: https://github.com/zdmooc/gitops-platform.git
    targetRevision: main
    path: apps
    directory:
      recurse: true
  syncPolicy:
    automated: {}
